# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edd8a3bcaaa93d981db5feef196b836fa2acd36ba6100699eb876f2fdbd7a4a4729ad0c534115b66a050484610a18731658f30b8ac697d206be26ad30b8de815

test:
  secret_key_base: e375e020e36e40da14a19e80a41f652209d4194f333cc793e3517af11da4f5acbdcec9d1db653ec0082ee72501924c30936bb4d6a7914421c0e608c8576253de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
